/**
 * Export paths out of the Studio:
 *  - a ready-to-run Expo SDK 57 project (.zip) with a README and personal
 *    LEARNING_NOTES.md generated from the Explain and Learn stages;
 *  - an embedded Expo Snack session, to run the app on a real phone via Expo Go.
 */
import JSZip from 'jszip';
import { CONCEPTS_BY_ID, LUNOR_ROADMAP } from '../../shared/concepts.ts';
import { resolveRange } from '../../shared/codeRefs.ts';
import { ALLOWED_PACKAGES, BASE_DEPENDENCIES, detectPackages } from '../../shared/runtimeContract.ts';
import type { Project } from './projects';

export function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'lunor-app';
}

const appName = (p: Project) => p.understanding?.appName ?? 'Lunor App';

export function projectDependencies(files: Record<string, string>): Record<string, string> {
  const deps: Record<string, string> = { ...BASE_DEPENDENCIES };
  for (const pkg of detectPackages(files)) {
    const allowed = ALLOWED_PACKAGES[pkg];
    if (allowed) deps[pkg] = allowed.version;
  }
  return Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b)));
}

function readme(p: Project): string {
  const u = p.understanding;
  const plan = p.plan;
  const excluded = new Set(p.excludedFeatures);
  const lines = [
    `# ${u?.emoji ?? '📱'} ${appName(p)}`,
    '',
    u?.tagline ? `> ${u.tagline}` : '',
    '',
    u?.summary ?? p.idea,
    '',
    `Built with **Lunor App Studio** · React Native + Expo SDK 57 · level: ${p.level}.`,
    '',
    '## Run it',
    '',
    '1. Install [Node.js](https://nodejs.org) 20 or newer.',
    '2. In this folder run `npm install`.',
    '3. Run `npx expo install --fix` to align package versions with your Expo SDK.',
    '4. Run `npx expo start` and scan the QR code with the **Expo Go** app (Android / iOS), or press `w` to open it in a browser.',
    '',
  ];
  const features = (u?.features ?? []).filter((f) => !excluded.has(f.id) && f.priority !== 'could');
  if (features.length) lines.push('## Features', '', ...features.map((f) => `- **${f.name}** — ${f.description}`), '');
  if (plan?.files?.length) {
    lines.push('## Project structure', '', '| File | Purpose |', '| --- | --- |', ...plan.files.filter((f) => f.path in p.files).map((f) => `| \`${f.path}\` | ${f.purpose} |`), '');
  }
  if (plan?.buildSteps?.length) {
    lines.push('## How it was built', '', ...plan.buildSteps.map((s, i) => `${i + 1}. **${s.title}** — ${s.description}`), '');
  }
  if (plan?.techStack?.length) lines.push('## Tech stack', '', ...plan.techStack.map((t) => `- **${t.name}** (${t.category}) — ${t.reason}`), '');
  if (plan?.futureIdeas?.length) lines.push('## Ideas for v2', '', ...plan.futureIdeas.map((i) => `- ${i}`), '');
  lines.push('See **LEARNING_NOTES.md** for a guided walkthrough of the code, the concepts it teaches, a quiz and practice challenges.', '');
  return lines.filter((line, i, all) => !(line === '' && all[i - 1] === '')).join('\n');
}

function learningNotes(p: Project): string {
  const lines = [`# Learning notes — ${appName(p)}`, '', `Generated by Lunor App Studio for a **${p.level}** learner.`, ''];
  const e = p.explanation;
  if (e) {
    lines.push('## How the app works', '', e.overview, '');
    if (e.dataFlow?.steps?.length) {
      lines.push(`### Data flow: ${e.dataFlow.scenario}`, '', ...e.dataFlow.steps.map((s, i) => `${i + 1}. **${s.title}** (\`${s.file}\`) — ${s.description}`), '');
    }
    lines.push('## Code walkthrough', '');
    for (const file of e.files ?? []) {
      lines.push(`### \`${file.path}\` — ${file.role}`, '', file.summary, '');
      for (const section of file.sections ?? []) {
        const range = resolveRange(p.files[file.path], section);
        lines.push(`- **${section.title}** (lines ${range.start}–${range.end}): ${section.explanation.replace(/\n+/g, ' ')}`);
      }
      lines.push('');
    }
    if (e.glossary?.length) lines.push('## Glossary', '', ...e.glossary.map((g) => `- **${g.term}** — ${g.definition}`), '');
  }
  const l = p.learn;
  if (l) {
    lines.push('## Concepts you practised', '', `_${l.headline}_`, '');
    for (const c of l.concepts ?? []) {
      const concept = CONCEPTS_BY_ID[c.conceptId];
      const level = concept ? LUNOR_ROADMAP[concept.lunorLevel - 1] : undefined;
      lines.push(`### ${concept?.name ?? c.conceptId}${level ? ` · Lunor level ${level.level}: ${level.title}` : ''}`, '', c.explanation, '', `**Why it matters:** ${c.whyItMatters}`, '', `**Try it:** ${c.practiceTip}`);
      if (concept) lines.push('', `Docs: ${concept.docsUrl}`);
      lines.push('');
    }
    if (l.quiz?.length) {
      lines.push('## Quiz', '');
      l.quiz.forEach((q, i) => {
        lines.push(`${i + 1}. ${q.question}`, ...q.options.map((o, j) => `   ${String.fromCharCode(65 + j)}. ${o}`));
        lines.push(`   <details><summary>Answer</summary>${String.fromCharCode(65 + q.answerIndex)} — ${q.explanation}</details>`, '');
      });
    }
    if (l.challenges?.length) {
      lines.push('## Challenges', '');
      for (const c of l.challenges) {
        lines.push(`### ${c.title} (${c.difficulty})`, '', c.description, '', '**Hints**', ...c.hints.map((h) => `- ${h}`), '', '**Done when**', ...c.acceptanceCriteria.map((a) => `- [ ] ${a}`), '');
      }
    }
    if (l.nextSteps?.length) {
      lines.push('## What to learn next', '', ...l.nextSteps.map((n) => `- **${CONCEPTS_BY_ID[n.conceptId]?.name ?? n.conceptId}** — ${n.reason}`), '');
    }
  }
  return lines.join('\n');
}

export async function exportExpoZip(project: Project): Promise<{ blob: Blob; filename: string }> {
  const slug = slugify(appName(project));
  const zip = new JSZip();
  const root = zip.folder(slug)!;
  root.file(
    'package.json',
    `${JSON.stringify(
      {
        name: slug,
        version: '1.0.0',
        main: 'index.js',
        private: true,
        scripts: { start: 'expo start', android: 'expo start --android', ios: 'expo start --ios', web: 'expo start --web' },
        dependencies: projectDependencies(project.files),
      },
      null,
      2,
    )}\n`,
  );
  root.file(
    'app.json',
    `${JSON.stringify({ expo: { name: appName(project), slug, version: '1.0.0', orientation: 'portrait', userInterfaceStyle: 'light', ios: { supportsTablet: false } } }, null, 2)}\n`,
  );
  root.file(
    'index.js',
    "import { registerRootComponent } from 'expo';\nimport App from './App';\n\n// Registers App as the root component for Expo Go and native builds.\nregisterRootComponent(App);\n",
  );
  root.file('.gitignore', 'node_modules/\n.expo/\ndist/\nweb-build/\n*.log\n.DS_Store\n');
  for (const [path, content] of Object.entries(project.files)) root.file(path, content);
  root.file('README.md', readme(project));
  if (project.explanation || project.learn) root.file('LEARNING_NOTES.md', learningNotes(project));
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  return { blob, filename: `${slug}.zip` };
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const SNACK_ORIGIN = 'https://snack.expo.dev';

/**
 * Snack's embed protocol (the one its official embed.js uses): the iframe
 * loads /embedded with `waitForData`, announces itself with
 * ['expoFrameLoaded', {iframeId}], and receives the project as
 * ['expoDataEvent', {iframeId, files, dependencies}]. Unlike the `files=`
 * URL parameter this has no size limit — a typical generated app is ~50 KB,
 * which Snack rejects as a URL (HTTP 431).
 */
export function snackEmbedUrl(project: Project, iframeId: string): string {
  const params: Record<string, string> = {
    iframeId,
    waitForData: 'true',
    preview: 'true',
    platform: 'mydevice',
    theme: 'dark',
    name: appName(project),
    description: project.understanding?.tagline ?? 'Built with Lunor App Studio',
  };
  const query = Object.entries(params)
    .map(([k, v]) => `${k}=${encodeURIComponent(v)}`)
    .join('&');
  return `${SNACK_ORIGIN}/embedded?${query}`;
}

/** Payload for the expoDataEvent message: `files` is a JSON string, `dependencies` a comma list (Snack picks SDK-compatible versions). */
export function snackData(project: Project, iframeId: string) {
  const files = Object.fromEntries(Object.entries(project.files).map(([path, contents]) => [path, { type: 'CODE', contents }]));
  const dependencies = detectPackages(project.files).filter((pkg) => pkg in ALLOWED_PACKAGES);
  return { iframeId, files: JSON.stringify(files), dependencies: dependencies.join(',') };
}
