/**
 * Replays a bundled sample through the exact same callbacks as a live AI
 * stream (thinking first, then output in chunks), so demo projects exercise
 * the real streaming UI — just without the wait or the API cost.
 */
import { toFileBlocks } from '../../shared/fileProtocol.ts';
import type { StageId } from '../../shared/schemas.ts';
import { loadSampleDoc, loadSampleFiles } from '../samples';
import { AIError, type StreamHandlers, type StreamResult } from './ai';

const DURATIONS: Record<StageId, number> = { understand: 2600, plan: 3200, build: 7000, explain: 2400, learn: 2400 };
const DOCS = { understand: 'understanding', plan: 'plan', explain: 'explanation', learn: 'learn' } as const;

function sleep(ms: number, signal?: AbortSignal) {
  return new Promise<void>((resolve, reject) => {
    if (signal?.aborted) return reject(new AIError('aborted', 'Cancelled.'));
    const timer = setTimeout(resolve, ms);
    signal?.addEventListener('abort', () => {
      clearTimeout(timer);
      reject(new AIError('aborted', 'Cancelled.'));
    }, { once: true });
  });
}

async function emit(text: string, durationMs: number, onChunk: (delta: string, all: string) => void, signal?: AbortSignal) {
  const frame = 24;
  const steps = Math.max(1, Math.round(durationMs / frame));
  const size = Math.max(1, Math.ceil(text.length / steps));
  let all = '';
  for (let i = 0; i < text.length; i += size) {
    await sleep(frame, signal);
    const delta = text.slice(i, i + size);
    all += delta;
    onChunk(delta, all);
  }
}

export async function replayStage(
  sampleId: string,
  stage: StageId,
  handlers: StreamHandlers,
  signal?: AbortSignal,
  options: { existingFiles?: Record<string, string> } = {},
): Promise<StreamResult> {
  const thinkingDoc = (await loadSampleDoc<Record<string, string>>(sampleId, 'thinking')) ?? {};
  handlers.onMeta?.({ model: 'instant demo (pre-generated by Claude)', mock: true });

  let text: string;
  if (stage === 'build') {
    const [files, plan] = await Promise.all([
      loadSampleFiles(sampleId),
      loadSampleDoc<{ buildSteps?: { files: string[] }[] }>(sampleId, 'plan'),
    ]);
    const order = (plan?.buildSteps ?? []).flatMap((s) => s.files);
    const rank = (p: string) => (p === 'App.js' ? 1e6 : order.includes(p) ? order.indexOf(p) : 1e5);
    const remaining = Object.entries(files)
      .filter(([path]) => !(path in (options.existingFiles ?? {})))
      .sort(([a], [b]) => rank(a) - rank(b));
    text = toFileBlocks(Object.fromEntries(remaining));
  } else {
    const doc = await loadSampleDoc<unknown>(sampleId, DOCS[stage]);
    if (!doc) throw new AIError('missing_sample', `This demo has no ${stage} data.`);
    text = JSON.stringify(doc);
  }

  const thinking = thinkingDoc[stage] ?? '';
  let thinkingAll = '';
  if (thinking) {
    await emit(thinking, Math.min(1400, thinking.length * 3), (d, all) => {
      thinkingAll = all;
      handlers.onThinking?.(d, all);
    }, signal);
  }
  await emit(text, DURATIONS[stage], (d, all) => handlers.onText?.(d, all), signal);
  return { text, thinking: thinkingAll, stopReason: 'end_turn', model: 'instant demo', interrupted: false };
}

/** Stream a canned mentor answer word by word. */
export async function replayText(text: string, handlers: StreamHandlers, signal?: AbortSignal): Promise<StreamResult> {
  await emit(text, Math.min(2200, text.length * 4), (d, all) => handlers.onText?.(d, all), signal);
  return { text, thinking: '', stopReason: 'end_turn', model: 'instant demo', interrupted: false };
}
